name: Moneylover reporter
on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: macos-latest
    env:
      GOOGLE_USER: ${{ secrets.GOOGLE_USER }}
      GOOGLE_PASSWORD : ${{ secrets.GOOGLE_PASSWORD }}
      MONEY_LOVER_USER: ${{ secrets.MONEY_LOVER_USER }}
      MONEY_LOVER_PASSWORD: ${{ secrets.MONEY_LOVER_PASSWORD }}
      SERPSBOT_API_KEY: ${{ secrets.SERPSBOT_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7.1'
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Install dependencies
        run: poetry install
      - name: Execute reporter
        run: poetry run python main.py
      - name: Keep alive 
        uses: gautamkrishnar/keepalive-workflow@v1
