name: Moneylover reporter
on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    env:
      GOOGLE_PASSWORD : ${{ secrets.GOOGLE_PASSWORD }}
      GOOGLE_USER: ${{ secrets.GOOGLE_USER }}
      MONEY_LOVER_PASSWORD: ${{ secrets.MONEY_LOVER_PASSWORD }}
      MONEY_LOVER_USER: ${{ secrets.MONEY_LOVER_USER }}
      RAPID_HOST: ${{ secrets.RAPID_HOST }}
      RAPID_KEY: ${{ secrets.RAPID_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Start selenium standalone
        run: |
          docker pull selenium/standalone-chrome
          docker run -d -p4444:4444 selenium/standalone-chrome
          docker ps
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python -
          poetry install
      - name: Execute reporter
        run: poetry run python main.py
