name: Moneylover reporter
on:
  schedule:
    - cron:  '0 6 * * *'
  workflow_dispatch:
jobs:
  cron:
    runs-on: macos-latest
    services:
      docker:
        image: docker:dind
        options: --privileged --shm-size=2g
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ros
    env:
      GOOGLE_USER: ${{ secrets.GOOGLE_USER }}
      GOOGLE_PASSWORD : ${{ secrets.GOOGLE_PASSWORD }}
      MONEY_LOVER_USER: ${{ secrets.MONEY_LOVER_USER }}
      MONEY_LOVER_PASSWORD: ${{ secrets.MONEY_LOVER_PASSWORD }}
      SERPSBOT_API_KEY: ${{ secrets.SERPSBOT_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install Docker
        run: |
          apt-get update
          apt-get install -y docker.io
      - name: Test Docker
        run: |
          docker version
          docker info 
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Build Docker Image
        run: docker build -t money-lover-reporter .
      - name: Execute reporter
        run: |
          docker run --rm \
            -e GOOGLE_USER=${{ secrets.GOOGLE_USER }} \
            -e GOOGLE_PASSWORD=${{ secrets.GOOGLE_PASSWORD }} \
            -e MONEY_LOVER_USER=${{ secrets.MONEY_LOVER_USER }} \
            -e MONEY_LOVER_PASSWORD=${{ secrets.MONEY_LOVER_PASSWORD }} \
            -e SERPSBOT_API_KEY=${{ secrets.SERPSBOT_API_KEY }} \
            money-lover-reporter
      - name: Keep alive 
        uses: gautamkrishnar/keepalive-workflow@v1
